export enum AdmissionType {
  UNDERGRADUATE = 'UNDERGRADUATE',
  GRADUATE = 'GRADUATE',
  TRANSFER = 'TRANSFER',
  INTERNATIONAL = 'INTERNATIONAL',
  CERTIFICATE = 'CERTIFICATE',
  ONLINE = 'ONLINE',
}

export enum AdmissionStatus {
  DRAFT = 'DRAFT',
  SUBMITTED = 'SUBMITTED',
  UNDER_REVIEW = 'UNDER_REVIEW',
  DOCUMENTS_REQUESTED = 'DOCUMENTS_REQUESTED',
  INTERVIEW_SCHEDULED = 'INTERVIEW_SCHEDULED',
  ACCEPTED = 'ACCEPTED',
  REJECTED = 'REJECTED',
  WAITLISTED = 'WAITLISTED',
  DEFERRED = 'DEFERRED',
  ENROLLED = 'ENROLLED',
  ENROLLMENT_COMPLETE = 'ENROLLMENT_COMPLETE',
}

export enum ApplicationTerm {
  FALL_2025 = 'FALL_2025',
  SPRING_2026 = 'SPRING_2026',
  SUMMER_2026 = 'SUMMER_2026',
  FALL_2026 = 'FALL_2026',
  SPRING_2027 = 'SPRING_2027',
}

export enum EnglishLevel {
  BEGINNER = 'BEGINNER',
  ELEMENTARY = 'ELEMENTARY',
  INTERMEDIATE = 'INTERMEDIATE',
  UPPER_INTERMEDIATE = 'UPPER_INTERMEDIATE',
  ADVANCED = 'ADVANCED',
  NATIVE = 'NATIVE',
}

export enum LanguageProficiency {
  BEGINNER = 'BEGINNER',
  ELEMENTARY = 'ELEMENTARY',
  INTERMEDIATE = 'INTERMEDIATE',
  ADVANCED = 'ADVANCED',
  NATIVE = 'NATIVE',
}

export enum QuestionType {
  READING = 'READING',
  WRITING = 'WRITING',
  LISTENING = 'LISTENING',
  SPEAKING = 'SPEAKING',
  GRAMMAR = 'GRAMMAR',
  VOCABULARY = 'VOCABULARY',
  MULTIPLE_CHOICE = 'MULTIPLE_CHOICE',
}

export enum QuestionDifficulty {
  EASY = 'EASY',
  MEDIUM = 'MEDIUM',
  HARD = 'HARD',
}

export enum TestCategory {
  GRAMMAR = 'GRAMMAR',
  VOCABULARY = 'VOCABULARY',
  READING = 'READING',
  WRITING = 'WRITING',
  LISTENING = 'LISTENING',
  SPEAKING = 'SPEAKING',
  COMPREHENSION = 'COMPREHENSION',
}

export enum TestType {
  PLACEMENT = 'PLACEMENT',
  CERTIFICATION = 'CERTIFICATION',
  SKILLS_ASSESSMENT = 'SKILLS_ASSESSMENT',
}

export enum NotificationType {
  ADMISSION_RECEIVED = 'ADMISSION_RECEIVED',
  ADMISSION_ACCEPTED = 'ADMISSION_ACCEPTED',
  ADMISSION_REJECTED = 'ADMISSION_REJECTED',
  ADMISSION_WAITLISTED = 'ADMISSION_WAITLISTED',
  DOCUMENT_REQUESTED = 'DOCUMENT_REQUESTED',
  INTERVIEW_SCHEDULED = 'INTERVIEW_SCHEDULED',
  DECISION_MADE = 'DECISION_MADE',
  ENROLLMENT_DEADLINE = 'ENROLLMENT_DEADLINE',
  PROFILE_VIEWED = 'PROFILE_VIEWED',
  MESSAGE = 'MESSAGE',
  ENGLISH_TEST_INVITE = 'ENGLISH_TEST_INVITE',
}

export enum AdmissionsStage {
  PROGRAM_DISCOVERY = 'PROGRAM_DISCOVERY',
  PROGRAM_SELECTION = 'PROGRAM_SELECTION',
  APPLICATION_SUBMITTED = 'APPLICATION_SUBMITTED',
  DOCUMENT_REVIEW = 'DOCUMENT_REVIEW',
  ENTRANCE_EXAM = 'ENTRANCE_EXAM',
  INTERVIEW = 'INTERVIEW',
  ADMISSION_DECISION = 'ADMISSION_DECISION',
  ENROLLMENT = 'ENROLLMENT',
  ORIENTATION = 'ORIENTATION',
  CLASSES_BEGIN = 'CLASSES_BEGIN',
}

export enum RegStatus {
  ENROLLED = 'ENROLLED',
  DROPPED = 'DROPPED',
  COMPLETED = 'COMPLETED',
}

export enum AnnouncementType {
  GENERAL = 'GENERAL',
  DEPARTMENT = 'DEPARTMENT',
  DEADLINE = 'DEADLINE',
}

export enum ConnectionType {
  DISCORD = 'DISCORD',
  SLACK = 'SLACK',
  NOTION = 'NOTION',
  GOOGLE = 'GOOGLE',
}
